FROM maven:3.9.6-eclipse-temurin-17

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gnupg \
    unzip \
    xvfb

# Install latest NodeJS
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

RUN apt-get install -y nodejs

# Install json-server
RUN npm install -g json-server

# Install Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

# Create working directory
WORKDIR /app

# Copy framework
COPY . .

# Install Maven dependencies
RUN mvn clean install -DskipTests

# Expose fake API port
EXPOSE 3000

# Start fake API and execute tests
CMD sh -c "\
json-server --watch fakeapi.json --port 3000 & \
sleep 15 && \
mvn clean test -DsuiteXmlFile=testrum.xml ; \
echo '=========================================' && \
echo 'Execution Completed' && \
echo 'Reports Available Under /app/Reports' && \
echo '=========================================' \
"